/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1___or___SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1____a;
	protected AbstractElementAlias match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a;
	protected AbstractElementAlias match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__p;
	protected AbstractElementAlias match_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__a;
	protected AbstractElementAlias match_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1___or___SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getNodesKeyword_3_0_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_0_1())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getSubsystemsKeyword_3_1_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_1_1())));
		match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a = new GroupAlias(true, true, new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getNodesKeyword_3_0_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_0_1())), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getSubsystemsKeyword_3_1_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_1_1()));
		match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__p = new GroupAlias(true, false, new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getNodesKeyword_3_0_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_0_1())), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getSubsystemsKeyword_3_1_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_1_1()));
		match_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__a = new GroupAlias(true, true, new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getSubsystemsKeyword_3_1_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_1_1())), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getNodesKeyword_3_0_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_0_1()));
		match_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__p = new GroupAlias(true, false, new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getSubsystemsKeyword_3_1_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_1_1())), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getNodesKeyword_3_0_0()), new TokenAlias(false, false, grammarAccess.getSystemDefinitionAccess().getColonKeyword_3_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1___or___SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1____a.equals(syntax))
				emit_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1___or___SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a.equals(syntax))
				emit_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__p.equals(syntax))
				emit_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__a.equals(syntax))
				emit_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__p.equals(syntax))
				emit_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (('nodes' ':') | ('subsystems' ':'))*
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '{' (ambiguity) '}' (rule end)
	 *     nodes+=NodeInstance ';' (ambiguity) '}' (rule end)
	 *     subsystems+=SystemInstance ';' (ambiguity) '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1___or___SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (('nodes' ':')* 'subsystems' ':')*
	 *
	 * This ambiguous syntax occurs at:
	 *     subsystems+=SystemInstance ';' (ambiguity) subsystems+=SystemInstance
	 
	 * </pre>
	 */
	protected void emit_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (('nodes' ':')* 'subsystems' ':')+
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '{' (ambiguity) subsystems+=SystemInstance
	 *     nodes+=NodeInstance ';' (ambiguity) subsystems+=SystemInstance
	 
	 * </pre>
	 */
	protected void emit_SystemDefinition_____NodesKeyword_3_0_0_ColonKeyword_3_0_1__a_SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (('subsystems' ':')* 'nodes' ':')*
	 *
	 * This ambiguous syntax occurs at:
	 *     nodes+=NodeInstance ';' (ambiguity) nodes+=NodeInstance
	 
	 * </pre>
	 */
	protected void emit_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (('subsystems' ':')* 'nodes' ':')+
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '{' (ambiguity) nodes+=NodeInstance
	 *     subsystems+=SystemInstance ';' (ambiguity) nodes+=NodeInstance
	 
	 * </pre>
	 */
	protected void emit_SystemDefinition_____SubsystemsKeyword_3_1_0_ColonKeyword_3_1_1__a_NodesKeyword_3_0_0_ColonKeyword_3_0_1__p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
