/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deployment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Deployment#getPlatforms <em>Platforms</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Deployment#getSystems <em>Systems</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Deployment#getDeployments <em>Deployments</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeployment()
 * @model
 * @generated
 */
public interface Deployment extends EObject
{
  /**
   * Returns the value of the '<em><b>Platforms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.PlatformInstance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Platforms</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeployment_Platforms()
   * @model containment="true"
   * @generated
   */
  EList<PlatformInstance> getPlatforms();

  /**
   * Returns the value of the '<em><b>Systems</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.SystemInstance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Systems</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeployment_Systems()
   * @model containment="true"
   * @generated
   */
  EList<SystemInstance> getSystems();

  /**
   * Returns the value of the '<em><b>Deployments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.DeploymentStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deployments</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeployment_Deployments()
   * @model containment="true"
   * @generated
   */
  EList<DeploymentStatement> getDeployments();

} // Deployment
