/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NODES = 0;

  /**
   * The feature id for the '<em><b>Systems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SYSTEMS = 1;

  /**
   * The feature id for the '<em><b>Deployments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DEPLOYMENTS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeDefinitionImpl <em>Node Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NodeDefinitionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeDefinition()
   * @generated
   */
  int NODE_DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DEFINITION__NAME = 0;

  /**
   * The number of structural features of the '<em>Node Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeInstanceImpl <em>Node Instance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NodeInstanceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeInstance()
   * @generated
   */
  int NODE_INSTANCE = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_INSTANCE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_INSTANCE__NAME = 1;

  /**
   * The number of structural features of the '<em>Node Instance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_INSTANCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemDefinitionImpl <em>System Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemDefinitionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemDefinition()
   * @generated
   */
  int SYSTEM_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEFINITION__NODES = 1;

  /**
   * The feature id for the '<em><b>Subsystems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEFINITION__SUBSYSTEMS = 2;

  /**
   * The number of structural features of the '<em>System Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemInstanceImpl <em>System Instance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemInstanceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemInstance()
   * @generated
   */
  int SYSTEM_INSTANCE = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_INSTANCE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_INSTANCE__NAME = 1;

  /**
   * The number of structural features of the '<em>System Instance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_INSTANCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SubSystemReferenceImpl <em>Sub System Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SubSystemReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubSystemReference()
   * @generated
   */
  int SUB_SYSTEM_REFERENCE = 5;

  /**
   * The number of structural features of the '<em>Sub System Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_SYSTEM_REFERENCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemReferenceImpl <em>System Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemReference()
   * @generated
   */
  int SYSTEM_REFERENCE = 6;

  /**
   * The feature id for the '<em><b>System</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_REFERENCE__SYSTEM = SUB_SYSTEM_REFERENCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>System Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_REFERENCE_FEATURE_COUNT = SUB_SYSTEM_REFERENCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DeploymentStatementImpl <em>Deployment Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DeploymentStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDeploymentStatement()
   * @generated
   */
  int DEPLOYMENT_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>System</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_STATEMENT__SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_STATEMENT__NODE = 1;

  /**
   * The feature id for the '<em><b>Platform</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_STATEMENT__PLATFORM = 2;

  /**
   * The number of structural features of the '<em>Deployment Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DeploymentImpl <em>Deployment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DeploymentImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDeployment()
   * @generated
   */
  int DEPLOYMENT = 8;

  /**
   * The feature id for the '<em><b>Platforms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT__PLATFORMS = 0;

  /**
   * The feature id for the '<em><b>Systems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT__SYSTEMS = 1;

  /**
   * The feature id for the '<em><b>Deployments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT__DEPLOYMENTS = 2;

  /**
   * The number of structural features of the '<em>Deployment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPLOYMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PlatformInstanceImpl <em>Platform Instance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PlatformInstanceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPlatformInstance()
   * @generated
   */
  int PLATFORM_INSTANCE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM_INSTANCE__NAME = 0;

  /**
   * The number of structural features of the '<em>Platform Instance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLATFORM_INSTANCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeInstanceReferenceImpl <em>Node Instance Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NodeInstanceReferenceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeInstanceReference()
   * @generated
   */
  int NODE_INSTANCE_REFERENCE = 10;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_INSTANCE_REFERENCE__REF = SUB_SYSTEM_REFERENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tail</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_INSTANCE_REFERENCE__TAIL = SUB_SYSTEM_REFERENCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Node Instance Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_INSTANCE_REFERENCE_FEATURE_COUNT = SUB_SYSTEM_REFERENCE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getNodes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Nodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getSystems <em>Systems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Systems</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getSystems()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Systems();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getDeployments <em>Deployments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Deployments</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getDeployments()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Deployments();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.NodeDefinition <em>Node Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Definition</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeDefinition
   * @generated
   */
  EClass getNodeDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.NodeDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeDefinition#getName()
   * @see #getNodeDefinition()
   * @generated
   */
  EAttribute getNodeDefinition_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.NodeInstance <em>Node Instance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Instance</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeInstance
   * @generated
   */
  EClass getNodeInstance();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.NodeInstance#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeInstance#getType()
   * @see #getNodeInstance()
   * @generated
   */
  EReference getNodeInstance_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.NodeInstance#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeInstance#getName()
   * @see #getNodeInstance()
   * @generated
   */
  EAttribute getNodeInstance_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SystemDefinition <em>System Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Definition</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemDefinition
   * @generated
   */
  EClass getSystemDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SystemDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemDefinition#getName()
   * @see #getSystemDefinition()
   * @generated
   */
  EAttribute getSystemDefinition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SystemDefinition#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemDefinition#getNodes()
   * @see #getSystemDefinition()
   * @generated
   */
  EReference getSystemDefinition_Nodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SystemDefinition#getSubsystems <em>Subsystems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subsystems</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemDefinition#getSubsystems()
   * @see #getSystemDefinition()
   * @generated
   */
  EReference getSystemDefinition_Subsystems();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SystemInstance <em>System Instance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Instance</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemInstance
   * @generated
   */
  EClass getSystemInstance();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.SystemInstance#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemInstance#getType()
   * @see #getSystemInstance()
   * @generated
   */
  EReference getSystemInstance_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SystemInstance#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemInstance#getName()
   * @see #getSystemInstance()
   * @generated
   */
  EAttribute getSystemInstance_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SubSystemReference <em>Sub System Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub System Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubSystemReference
   * @generated
   */
  EClass getSubSystemReference();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SystemReference <em>System Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemReference
   * @generated
   */
  EClass getSystemReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.SystemReference#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>System</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemReference#getSystem()
   * @see #getSystemReference()
   * @generated
   */
  EReference getSystemReference_System();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DeploymentStatement <em>Deployment Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deployment Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.DeploymentStatement
   * @generated
   */
  EClass getDeploymentStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.DeploymentStatement#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>System</em>'.
   * @see org.xtext.example.mydsl.myDsl.DeploymentStatement#getSystem()
   * @see #getDeploymentStatement()
   * @generated
   */
  EReference getDeploymentStatement_System();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.DeploymentStatement#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Node</em>'.
   * @see org.xtext.example.mydsl.myDsl.DeploymentStatement#getNode()
   * @see #getDeploymentStatement()
   * @generated
   */
  EReference getDeploymentStatement_Node();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.DeploymentStatement#getPlatform <em>Platform</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Platform</em>'.
   * @see org.xtext.example.mydsl.myDsl.DeploymentStatement#getPlatform()
   * @see #getDeploymentStatement()
   * @generated
   */
  EReference getDeploymentStatement_Platform();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Deployment <em>Deployment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deployment</em>'.
   * @see org.xtext.example.mydsl.myDsl.Deployment
   * @generated
   */
  EClass getDeployment();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Deployment#getPlatforms <em>Platforms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Platforms</em>'.
   * @see org.xtext.example.mydsl.myDsl.Deployment#getPlatforms()
   * @see #getDeployment()
   * @generated
   */
  EReference getDeployment_Platforms();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Deployment#getSystems <em>Systems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Systems</em>'.
   * @see org.xtext.example.mydsl.myDsl.Deployment#getSystems()
   * @see #getDeployment()
   * @generated
   */
  EReference getDeployment_Systems();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Deployment#getDeployments <em>Deployments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Deployments</em>'.
   * @see org.xtext.example.mydsl.myDsl.Deployment#getDeployments()
   * @see #getDeployment()
   * @generated
   */
  EReference getDeployment_Deployments();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.PlatformInstance <em>Platform Instance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Platform Instance</em>'.
   * @see org.xtext.example.mydsl.myDsl.PlatformInstance
   * @generated
   */
  EClass getPlatformInstance();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PlatformInstance#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.PlatformInstance#getName()
   * @see #getPlatformInstance()
   * @generated
   */
  EAttribute getPlatformInstance_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference <em>Node Instance Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Instance Reference</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeInstanceReference
   * @generated
   */
  EClass getNodeInstanceReference();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeInstanceReference#getRef()
   * @see #getNodeInstanceReference()
   * @generated
   */
  EReference getNodeInstanceReference_Ref();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getTail <em>Tail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tail</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeInstanceReference#getTail()
   * @see #getNodeInstanceReference()
   * @generated
   */
  EReference getNodeInstanceReference_Tail();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__NODES = eINSTANCE.getModel_Nodes();

    /**
     * The meta object literal for the '<em><b>Systems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SYSTEMS = eINSTANCE.getModel_Systems();

    /**
     * The meta object literal for the '<em><b>Deployments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DEPLOYMENTS = eINSTANCE.getModel_Deployments();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeDefinitionImpl <em>Node Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NodeDefinitionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeDefinition()
     * @generated
     */
    EClass NODE_DEFINITION = eINSTANCE.getNodeDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_DEFINITION__NAME = eINSTANCE.getNodeDefinition_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeInstanceImpl <em>Node Instance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NodeInstanceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeInstance()
     * @generated
     */
    EClass NODE_INSTANCE = eINSTANCE.getNodeInstance();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_INSTANCE__TYPE = eINSTANCE.getNodeInstance_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_INSTANCE__NAME = eINSTANCE.getNodeInstance_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemDefinitionImpl <em>System Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemDefinitionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemDefinition()
     * @generated
     */
    EClass SYSTEM_DEFINITION = eINSTANCE.getSystemDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_DEFINITION__NAME = eINSTANCE.getSystemDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEFINITION__NODES = eINSTANCE.getSystemDefinition_Nodes();

    /**
     * The meta object literal for the '<em><b>Subsystems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEFINITION__SUBSYSTEMS = eINSTANCE.getSystemDefinition_Subsystems();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemInstanceImpl <em>System Instance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemInstanceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemInstance()
     * @generated
     */
    EClass SYSTEM_INSTANCE = eINSTANCE.getSystemInstance();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_INSTANCE__TYPE = eINSTANCE.getSystemInstance_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_INSTANCE__NAME = eINSTANCE.getSystemInstance_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SubSystemReferenceImpl <em>Sub System Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SubSystemReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubSystemReference()
     * @generated
     */
    EClass SUB_SYSTEM_REFERENCE = eINSTANCE.getSubSystemReference();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemReferenceImpl <em>System Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemReference()
     * @generated
     */
    EClass SYSTEM_REFERENCE = eINSTANCE.getSystemReference();

    /**
     * The meta object literal for the '<em><b>System</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_REFERENCE__SYSTEM = eINSTANCE.getSystemReference_System();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DeploymentStatementImpl <em>Deployment Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DeploymentStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDeploymentStatement()
     * @generated
     */
    EClass DEPLOYMENT_STATEMENT = eINSTANCE.getDeploymentStatement();

    /**
     * The meta object literal for the '<em><b>System</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT_STATEMENT__SYSTEM = eINSTANCE.getDeploymentStatement_System();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT_STATEMENT__NODE = eINSTANCE.getDeploymentStatement_Node();

    /**
     * The meta object literal for the '<em><b>Platform</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT_STATEMENT__PLATFORM = eINSTANCE.getDeploymentStatement_Platform();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DeploymentImpl <em>Deployment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DeploymentImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDeployment()
     * @generated
     */
    EClass DEPLOYMENT = eINSTANCE.getDeployment();

    /**
     * The meta object literal for the '<em><b>Platforms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT__PLATFORMS = eINSTANCE.getDeployment_Platforms();

    /**
     * The meta object literal for the '<em><b>Systems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT__SYSTEMS = eINSTANCE.getDeployment_Systems();

    /**
     * The meta object literal for the '<em><b>Deployments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPLOYMENT__DEPLOYMENTS = eINSTANCE.getDeployment_Deployments();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PlatformInstanceImpl <em>Platform Instance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PlatformInstanceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPlatformInstance()
     * @generated
     */
    EClass PLATFORM_INSTANCE = eINSTANCE.getPlatformInstance();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLATFORM_INSTANCE__NAME = eINSTANCE.getPlatformInstance_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeInstanceReferenceImpl <em>Node Instance Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NodeInstanceReferenceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeInstanceReference()
     * @generated
     */
    EClass NODE_INSTANCE_REFERENCE = eINSTANCE.getNodeInstanceReference();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_INSTANCE_REFERENCE__REF = eINSTANCE.getNodeInstanceReference_Ref();

    /**
     * The meta object literal for the '<em><b>Tail</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_INSTANCE_REFERENCE__TAIL = eINSTANCE.getNodeInstanceReference_Tail();

  }

} //MyDslPackage
