/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Instance Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getBelongingSystemReference <em>Belonging System Reference</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getNode <em>Node</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstanceReference()
 * @model
 * @generated
 */
public interface NodeInstanceReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Belonging System Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Belonging System Reference</em>' containment reference.
   * @see #setBelongingSystemReference(SystemReference)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstanceReference_BelongingSystemReference()
   * @model containment="true"
   * @generated
   */
  SystemReference getBelongingSystemReference();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getBelongingSystemReference <em>Belonging System Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Belonging System Reference</em>' containment reference.
   * @see #getBelongingSystemReference()
   * @generated
   */
  void setBelongingSystemReference(SystemReference value);

  /**
   * Returns the value of the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' reference.
   * @see #setNode(NodeInstance)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstanceReference_Node()
   * @model
   * @generated
   */
  NodeInstance getNode();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getNode <em>Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' reference.
   * @see #getNode()
   * @generated
   */
  void setNode(NodeInstance value);

} // NodeInstanceReference
