/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NodeInstance#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstance()
 * @model
 * @generated
 */
public interface NodeInstance extends Feature
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(NodeDefinition)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstance_Type()
   * @model
   * @generated
   */
  NodeDefinition getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NodeInstance#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(NodeDefinition value);

} // NodeInstance
