/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Instance Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getRef <em>Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getTail <em>Tail</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstanceReference()
 * @model
 * @generated
 */
public interface NodeInstanceReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(NodeInstanceReference)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstanceReference_Ref()
   * @model containment="true"
   * @generated
   */
  NodeInstanceReference getRef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(NodeInstanceReference value);

  /**
   * Returns the value of the '<em><b>Tail</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tail</em>' reference.
   * @see #setTail(Feature)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNodeInstanceReference_Tail()
   * @model
   * @generated
   */
  Feature getTail();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NodeInstanceReference#getTail <em>Tail</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tail</em>' reference.
   * @see #getTail()
   * @generated
   */
  void setTail(Feature value);

} // NodeInstanceReference
