/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SystemInstance#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemInstance()
 * @model
 * @generated
 */
public interface SystemInstance extends Feature
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(SystemDefinition)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemInstance_Type()
   * @model
   * @generated
   */
  SystemDefinition getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SystemInstance#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(SystemDefinition value);

} // SystemInstance
