/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SystemReference#getSystem <em>System</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SystemReference#getSubsystem <em>Subsystem</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemReference()
 * @model
 * @generated
 */
public interface SystemReference extends EObject
{
  /**
   * Returns the value of the '<em><b>System</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' reference.
   * @see #setSystem(SystemInstance)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemReference_System()
   * @model
   * @generated
   */
  SystemInstance getSystem();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SystemReference#getSystem <em>System</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System</em>' reference.
   * @see #getSystem()
   * @generated
   */
  void setSystem(SystemInstance value);

  /**
   * Returns the value of the '<em><b>Subsystem</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subsystem</em>' reference.
   * @see #setSubsystem(SystemReference)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystemReference_Subsystem()
   * @model
   * @generated
   */
  SystemReference getSubsystem();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SystemReference#getSubsystem <em>Subsystem</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subsystem</em>' reference.
   * @see #getSubsystem()
   * @generated
   */
  void setSubsystem(SystemReference value);

} // SystemReference
