/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.scoping;

import com.google.common.base.Objects;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.xbase.lib.InputOutput;
import org.xtext.example.mydsl.myDsl.DeploymentStatement;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.SubSystemReference;
import org.xtext.example.mydsl.myDsl.SystemReference;

@SuppressWarnings("all")
public class MyDslScopeProvider extends AbstractMyDslScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    IScope _switchResult = null;
    boolean _matched = false;
    if (context instanceof SubSystemReference) {
      boolean _equals = Objects.equal(reference, MyDslPackage.Literals.SYSTEM_REFERENCE__SYSTEM);
      if (_equals) {
        _matched=true;
        _switchResult = this.getScopeForSubSystemReference_SubSystem(((SubSystemReference)context), reference);
      }
    }
    if (!_matched) {
      if (context instanceof DeploymentStatement) {
        boolean _equals = Objects.equal(reference, MyDslPackage.Literals.DEPLOYMENT_STATEMENT__NODE);
        if (_equals) {
          _matched=true;
          _switchResult = this.getScopeForDeploymentStatement_node(((DeploymentStatement)context), reference);
        }
      }
    }
    if (!_matched) {
      _switchResult = super.getScope(context, reference);
    }
    return _switchResult;
  }
  
  private IScope getScopeForSubSystemReference_SubSystem(final SubSystemReference subSysRef, final EReference reference) {
    return Scopes.scopeFor(subSysRef.getParent().getSystem().getType().getSubsystems());
  }
  
  private IScope getScopeForDeploymentStatement_node(final DeploymentStatement deployment, final EReference reference) {
    InputOutput.<String>println(MyDslScopeProvider.getName(deployment.getSystemRef()));
    return Scopes.scopeFor(deployment.getSystemRef().getSystem().getType().getNodes());
  }
  
  public static String getName(final SystemReference ref) {
    String _switchResult = null;
    boolean _matched = false;
    if (ref instanceof SubSystemReference) {
      _matched=true;
      String _name = MyDslScopeProvider.getName(((SubSystemReference)ref).getParent());
      String _plus = (_name + "_");
      String _name_1 = ((SubSystemReference)ref).getSystem().getName();
      _switchResult = (_plus + _name_1);
    }
    if (!_matched) {
      if (ref instanceof SystemReference) {
        _matched=true;
        _switchResult = ref.getSystem().getName();
      }
    }
    if (!_matched) {
      _switchResult = "";
    }
    return _switchResult;
  }
}
