/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.SubSystemReference;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sub System Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SubSystemReferenceImpl extends MinimalEObjectImpl.Container implements SubSystemReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubSystemReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SUB_SYSTEM_REFERENCE;
  }

} //SubSystemReferenceImpl
