/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.tasks.Priority;
import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.myDsl.DeploymentStatement;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.NodeInstance;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidator extends AbstractMyDslValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	@Check
	public void checkSystemNotUsedAsNodeInstance(DeploymentStatement stmt) {
		if(stmt.getNode().getName() == null) {
			error("Not a node instance", MyDslPackage.Literals.DEPLOYMENT_STATEMENT__NODE);
		}
	}
}
